import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import './globals.css'
import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>
        <div className="h-full w-full flex flex-col items-center bg-gradient-to-r from-[#8234d5] to-[#4e0a97] overflow-hidden relative">
          <Navbar/>
          {children}
          <Toaster />
        </div>
      </body>
      </AuthProvider>
    </html>
  );
}
